const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
(async()=>{
 const source=fs.readFileSync(require.resolve('../backend/services/llm-service'),'utf8').replace(/\r\n/g,'\n');
 let content, captured;
 const context={executeChatCompletion:async messages=>{captured=messages;return {content};}};
 vm.createContext(context);vm.runInContext(source.slice(source.indexOf('async function planActions('),source.indexOf('/**\n * Test LLM connection'))+'\nthis.plan=planActions;',context);
 content=JSON.stringify({actions:['Survey rail connections in Rome.','Consult France on trade.','Survey rail connections in Rome.']});
 assert.deepEqual(Array.from(await context.plan('Improve transport',{scenarioId:'ww1-1910',worldContext:'Qing rule continues.'})),['Survey rail connections in Rome.','Consult France on trade.']);
 assert(captured[1].content.includes('Improve transport'));assert(captured[1].content.includes('Qing rule continues.'));
 content='Here is my analysis of your question.';await assert.rejects(()=>context.plan('',{}),/did not return action drafts/);
 content='{"actions":[42]}';await assert.rejects(()=>context.plan('',{}),/invalid action drafts/);
 const panels={app:{currentGame:{saveId:'fixture'}},api:{getActions:async()=>[{id:'pending',status:'pending'},{id:'done',status:'completed'},{id:'old-rejected',status:'rejected'}]}};
 vm.createContext(panels);vm.runInContext(fs.readFileSync(require.resolve('../frontend/js/panels/actions-panel.js'),'utf8')+'\nthis.actions=actionsPanel;',panels);
 panels.actions.renderPendingActions=()=>{};await panels.actions.loadPendingActions();assert.deepEqual(Array.from(panels.actions.pendingActions,a=>a.id),['pending']);
 const timing={};vm.createContext(timing);vm.runInContext(fs.readFileSync(require.resolve('../frontend/js/panels/timeline-panel.js'),'utf8')+'\nthis.timeline=timelinePanel;',timing);
 assert.equal(timing.timeline.targetDate('1910-01-31','1_month').toISOString().slice(0,10),'1910-02-28');
 assert.equal(timing.timeline.targetDate('2012-01-31','1_month').toISOString().slice(0,10),'2012-02-29');
 assert.equal(timing.timeline.targetDate('1910-01-01','1_month').toISOString().slice(0,10),'1910-02-01');
 const flags={};vm.createContext(flags);vm.runInContext(fs.readFileSync(require.resolve('../frontend/js/flags.js'),'utf8')+'\nthis.flags=countryFlags;',flags);
 flags.flags.data=JSON.parse(fs.readFileSync(require.resolve('../data/flags/catalog.json'),'utf8'));
 assert.match(flags.flags.resolve('ITA','ww1-1910','1910-01-01').name,/1861/);
 assert.match(flags.flags.resolve('ITA','world-2010','2010-01-01').name,/Italy/);
 assert.equal(flags.flags.resolve('ENG','ww2-geographic','1936-01-01').name,'United Kingdom');
 assert.match(flags.flags.resolve('GER','ww1-1910','1910-01-01').name,/1867/);
 assert.match(flags.flags.resolve('GER','ww2-geographic','1936-01-01').name,/1935/);
 assert.match(flags.flags.resolve('USA','ww1-1910','1910-01-01').name,/1908/);
 assert.match(flags.flags.resolve('USA','ww2-geographic','1936-01-01').name,/1912/);
 for(const [scenario,nations] of Object.entries(flags.flags.data.scenarios))for(const entry of Object.values(nations))for(const id of entry.variants)assert(fs.existsSync(require('node:path').join(__dirname,'../frontend',flags.flags.data.flags[id].file)));
 console.log('✓ Action drafts, pending-only queue, calendar previews and dated flag assets passed');
})().catch(e=>{console.error(e);process.exitCode=1;});
